using System;

namespace Diffraction.WpfPrototype.Models
{

public sealed class EnergyDemoSnapshot
{
    public EnergyDemoSnapshot(
        double skinDepth,
        double reflectedScattered,
        double forwardScattered,
        double absorbed,
        double sheetAbove,
        double sheetBelow,
        double fluxAbsorbed,
        double localBalanceErrorPercent)
    {
        SkinDepth = skinDepth;
        ReflectedScattered = reflectedScattered;
        ForwardScattered = forwardScattered;
        Absorbed = absorbed;
        SheetAbove = sheetAbove;
        SheetBelow = sheetBelow;
        FluxAbsorbed = fluxAbsorbed;
        LocalBalanceErrorPercent = localBalanceErrorPercent;
    }

    public double SkinDepth { get; }
    public double ReflectedScattered { get; }
    public double ForwardScattered { get; }
    public double Absorbed { get; }
    public double SheetAbove { get; }
    public double SheetBelow { get; }
    public double FluxAbsorbed { get; }
    public double LocalBalanceErrorPercent { get; }

    public double FarFieldMismatchPercent =>
        Math.Abs(ReflectedScattered - ForwardScattered) * 100.0;

    public double SheetMismatchPercent =>
        Math.Abs(SheetAbove - SheetBelow) * 100.0;

    public double LocalBalanceTotal =>
        1.0 - LocalBalanceErrorPercent / 100.0;

    public string ReflectedDisplay => $"{ReflectedScattered:0.000}";
    public string ForwardDisplay => $"{ForwardScattered:0.000}";
    public string AbsorbedDisplay => $"{Absorbed:0.000}";
    public string SkinDepthDisplay => $"{SkinDepth:0.000000}";
    public string ReflectedPercentDisplay => $"{ReflectedScattered:P1} от I_plate";
    public string ForwardPercentDisplay => $"{ForwardScattered:P1} от I_plate";
    public string AbsorbedPercentDisplay => $"{Absorbed:P1} от I_plate";
    public string LocalBalanceErrorDisplay => $"{LocalBalanceErrorPercent:0.000}%";
    public string LocalBalanceResidualDisplay =>
        $"|ΔЗСЭ| / I_plate = {LocalBalanceErrorPercent:0.000}%";
    public string CompactBalanceDisplay =>
        $"ЗСЭ в допуске  •  |Δ| / I_plate = {LocalBalanceErrorPercent:0.000}%";
    public string SheetPairDisplay => $"{SheetAbove:0.000} / {SheetBelow:0.000}";
    public string DiagnosticsSummary =>
        $"Локальный ЗСЭ: невязка {LocalBalanceErrorPercent:0.000}% (допуск 2,00%).\n" +
        $"R_scat / T_scat: {ReflectedScattered:0.000000} / {ForwardScattered:0.000000}; совпадают в пределах машинной точности.\n" +
        $"Потоки рассеяния сверху / снизу у листа: {SheetAbove:0.000000} / {SheetBelow:0.000000}.\n" +
        "T_scat — рассеянное поле вперёд; полное прохождение дополнительно учитывает падающее поле и интерференцию.";
}

public static class ValidatedEnergyDemo
{
    // Generated by Diffraction.Core for one plate [-1.5; -0.5], lambda=1,
    // theta=45 degrees and N=30. Values are normalized by I_plate.
    public static EnergyDemoSnapshot Selected { get; } = new EnergyDemoSnapshot(
        skinDepth: 0.01,
        reflectedScattered: 0.8626996341671146,
        forwardScattered: 0.8626996341671144,
        absorbed: 0.1159575597470231,
        sheetAbove: 0.8596514326575219,
        sheetBelow: 0.8596514326575219,
        fluxAbsorbed: 0.1164282883935220,
        localBalanceErrorPercent: 0.0470728646498805);

    private static readonly double[] SkinDepths =
    {
        0.0, 0.001, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045,
        0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1
    };

    private static readonly double[] ScatteringBySkin =
    {
        0.9962685338758368, 0.9789497545802383, 0.9221586488637391,
        0.8626996341671146, 0.8106691257252682, 0.7640790918516919,
        0.7218596159222070, 0.6833091254057744, 0.6479183107093919,
        0.6152939238585323, 0.5851197335541266, 0.5571341431178170,
        0.5311162700514501, 0.5068767286938694, 0.4842512153541195,
        0.4630958594346867, 0.4432837401539467, 0.4247022033368085,
        0.4072507461540763, 0.3908393169493932, 0.3753869262256747,
        0.3608204961050888
    };

    private static readonly double[] AbsorptionBySkin =
    {
        0.0, 0.0153283042191518, 0.0660920893012907, 0.1159575597470231,
        0.1568087646563386, 0.1912401274965177, 0.2206739502168280,
        0.2460456859867342, 0.2680308728937174, 0.2871453749461705,
        0.3037977804093768, 0.3183200402626648, 0.3309868847098696,
        0.3420288952206398, 0.3516417267067267, 0.3599928582843355,
        0.3672266831670988, 0.3734684393904363, 0.3788273055945173,
        0.3833988792432562, 0.3872671876966110, 0.3905063391027765
    };

    private static readonly double[] BalanceErrorPercentBySkin =
    {
        0.0000000000577319, 0.0361599795740684, 0.0454765429369201,
        0.0470728646498805, 0.0467845257408992, 0.0458176065389984,
        0.0446128189848002, 0.0433397234398629, 0.0420700330336539,
        0.0408355826255811, 0.0396502932073874, 0.0385194794630746,
        0.0374441513314849, 0.0364231363235519, 0.0354541782214119,
        0.0345345251406520, 0.0336612504419416, 0.0328314285728178,
        0.0320422298707404, 0.0312909691837907, 0.0305751278716331,
        0.0298923604351734
    };

    private static readonly double[] IncidentAngles =
    {
        10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
        44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
        78, 80, 82, 84, 86, 88, 90
    };

    private static readonly double[] ScatteringByAngle =
    {
        2.2979627925904880, 1.9437849918200709, 1.6954432578252558,
        1.5133067867872123, 1.3753604798213541, 1.2683948475193874,
        1.1840011852401682, 1.1165689726747501, 1.0622074132787775,
        1.0181290883434615, 0.9822801249475397, 0.9531090879399502,
        0.9294175401645635, 0.9102605809426067, 0.8948790212584427,
        0.8826521929927175, 0.8730645797960756, 0.8656819293117692,
        0.8601340069403324, 0.8561020847730418, 0.8533098525560943,
        0.8515168218019662, 0.8505135475667210, 0.8501181627668131,
        0.8501738372235052, 0.8505468571671618, 0.8511250833009774,
        0.8518165950072542, 0.8525483702867153, 0.8532648889336523,
        0.8539265821645801, 0.8545080862151652, 0.8549962902351560,
        0.8553881994659375, 0.8556886621021725, 0.8559080311486846,
        0.8560598497263542, 0.8561586585950620, 0.8562180274452782,
        0.8562489065437612, 0.8562583829389787
    };

    public static double ScatteringAtSkinDepth(double skinDepth) =>
        Interpolate(skinDepth, SkinDepths, ScatteringBySkin);

    public static double AbsorptionAtSkinDepth(double skinDepth) =>
        Interpolate(skinDepth, SkinDepths, AbsorptionBySkin);

    public static double BalanceErrorPercentAtSkinDepth(double skinDepth) =>
        Interpolate(skinDepth, SkinDepths, BalanceErrorPercentBySkin);

    public static double ScatteringAtAngle(double angleDegrees) =>
        Interpolate(angleDegrees, IncidentAngles, ScatteringByAngle);

    private static double Interpolate(double argument, double[] arguments, double[] values)
    {
        if (argument <= arguments[0])
            return values[0];
        if (argument >= arguments[arguments.Length - 1])
            return values[values.Length - 1];

        int upper = Array.BinarySearch(arguments, argument);
        if (upper >= 0)
            return values[upper];

        upper = ~upper;
        int lower = upper - 1;
        double fraction = (argument - arguments[lower]) / (arguments[upper] - arguments[lower]);
        return values[lower] + fraction * (values[upper] - values[lower]);
    }
}
}
